// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApwBCZy_TeEBBHlJmesMa3OaAug1wotg4',
    appId: '1:140725637057:web:81954497560188fe5e2940',
    messagingSenderId: '140725637057',
    projectId: 'push-notification-js-e6a88',
    authDomain: 'push-notification-js-e6a88.firebaseapp.com',
    storageBucket: 'push-notification-js-e6a88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsaMmQBKJNVtdX5xoJtVsc9A190ngJl8',
    appId: '1:140725637057:android:29e8b2c42f2e4e5b5e2940',
    messagingSenderId: '140725637057',
    projectId: 'push-notification-js-e6a88',
    storageBucket: 'push-notification-js-e6a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyf7wVwXtxwhIG0OQu4VcD0jgE5f4f3nU',
    appId: '1:140725637057:ios:60607b6ac42f6e7b5e2940',
    messagingSenderId: '140725637057',
    projectId: 'push-notification-js-e6a88',
    storageBucket: 'push-notification-js-e6a88.appspot.com',
    iosBundleId: 'com.example.placementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyf7wVwXtxwhIG0OQu4VcD0jgE5f4f3nU',
    appId: '1:140725637057:ios:60607b6ac42f6e7b5e2940',
    messagingSenderId: '140725637057',
    projectId: 'push-notification-js-e6a88',
    storageBucket: 'push-notification-js-e6a88.appspot.com',
    iosBundleId: 'com.example.placementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApwBCZy_TeEBBHlJmesMa3OaAug1wotg4',
    appId: '1:140725637057:web:c42840d5997141305e2940',
    messagingSenderId: '140725637057',
    projectId: 'push-notification-js-e6a88',
    authDomain: 'push-notification-js-e6a88.firebaseapp.com',
    storageBucket: 'push-notification-js-e6a88.appspot.com',
  );
}
